name: BridgePracticeLobby
version: 1.0
api-version: 1.8
main: net.bridgepractice.BridgePracticeLobby.BridgePracticeLobby
depend: [ProtocolLib, LuckPerms]

commands:
  rainbow:
    description: Makes your text rainbow! Only available to certain ranked players
    permission: bridgepractice.command.rainbow
    permission-message: §cYou must have a godlike rank or higher to use this command!
  fw:
    description: Launch a firework!
    permission: bridgepractice.command.fw
    permission-message: §cYou must have a rank to use this command!
  cookie:
    description: Gives you the cookie gadget. Have a bite!
    permission: bridgepractice.command.cookie
    permission-message: §cYou must have a rank to use this command!
  joinannounce:
    description: Toggle join announcements in chat
    permission: bridgepractice.lobby.announce
    permission-message: §cYou must have a rank to use this command!
    usage: /<command> [on|off]
  stats:
    description: Get yours and other people's stats!
    usage: /<command> [player]
  telestick:
    description: Get a stick that makes you teleport!
    permission: bridgepractice.command.telestick
    permission-message: §cYou must have a godlike rank or higher to use this command!
  playerrider:
    description: Get a leash that lets you ride other players
    permission: group.custom
    permission-message: §cYou must have a custom rank or higher to use this command!
  enderbutt:
    description: Get a pearl that you can ride 
    permission: group.legend
    permission-message: §cYou must have legend rank or higher to use this command!
  coins:
    description: Staff only command
    permission: group.mod
    permission-message: §cYou don't have permission to execute this command

